# Generated by Django 4.2 on 2023-04-22 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockforecast', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='name',
            new_name='lastprice',
        ),
    ]
