# Generated by Django 4.2 on 2023-04-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockforecast', '0003_stockprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockprice',
            name='symbols',
            field=models.CharField(default='', max_length=10),
        ),
    ]
