# Generated by Django 4.2 on 2023-04-23 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockforecast', '0004_stockprice_symbols'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockprice',
            old_name='symbols',
            new_name='symbol',
        ),
    ]
