# Generated by Django 4.2 on 2023-04-26 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockforecast', '0006_alter_stockprice_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockprice',
            name='adj_close_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
