# Generated by Django 4.2 on 2023-04-26 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockforecast', '0007_stockprice_adj_close_price'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stockprice',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='stockprice',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='stockforecast.stock'),
        ),
        migrations.RemoveField(
            model_name='stockprice',
            name='stock',
        ),
    ]
