# Generated by Django 4.2 on 2023-04-26 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockforecast', '0008_alter_stockprice_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockprice',
            name='symbol',
        ),
        migrations.AddField(
            model_name='stockprice',
            name='stock',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='stockforecast.stock'),
        ),
    ]
