# Generated by Django 4.2 on 2023-04-26 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockforecast', '0009_remove_stockprice_symbol_stockprice_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockprice',
            name='adj_close_price',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockprice',
            name='close_price',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockprice',
            name='high_price',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockprice',
            name='low_price',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockprice',
            name='open_price',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
    ]
