# Generated by Django 4.2 on 2023-04-26 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockforecast', '0010_alter_stockprice_adj_close_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPricePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('predicted_price', models.DecimalField(decimal_places=6, max_digits=10)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockforecast.stock')),
            ],
        ),
    ]
