# Generated by Django 4.2 on 2023-05-03 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockforecast', '0011_stockpriceprediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='name',
            field=models.CharField(default='NA', max_length=255),
        ),
    ]
