# Generated by Django 4.2 on 2023-05-04 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockforecast', '0012_stock_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockPricePrediction',
        ),
    ]
