# Generated by Django 4.2 on 2023-05-04 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockforecast', '0014_lstmforecastedvalue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lstmforecastedvalue',
            name='next_five_days_values',
        ),
        migrations.RemoveField(
            model_name='lstmforecastedvalue',
            name='next_five_months_values',
        ),
        migrations.RemoveField(
            model_name='lstmforecastedvalue',
            name='next_five_weeks_values',
        ),
        migrations.RemoveField(
            model_name='lstmforecastedvalue',
            name='next_five_years_values',
        ),
        migrations.AddField(
            model_name='lstmforecastedvalue',
            name='next_1_day',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='lstmforecastedvalue',
            name='next_1_month',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='lstmforecastedvalue',
            name='next_1_week',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='lstmforecastedvalue',
            name='next_1_year',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='lstmforecastedvalue',
            name='next_2_day',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='lstmforecastedvalue',
            name='next_2_month',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='lstmforecastedvalue',
            name='next_2_week',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='lstmforecastedvalue',
            name='next_2_year',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='lstmforecastedvalue',
            name='next_3_day',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='lstmforecastedvalue',
            name='next_3_month',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='lstmforecastedvalue',
            name='next_3_week',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='lstmforecastedvalue',
            name='next_3_year',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='lstmforecastedvalue',
            name='next_4_day',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='lstmforecastedvalue',
            name='next_4_month',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='lstmforecastedvalue',
            name='next_4_week',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='lstmforecastedvalue',
            name='next_4_year',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='lstmforecastedvalue',
            name='next_5_day',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='lstmforecastedvalue',
            name='next_5_month',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='lstmforecastedvalue',
            name='next_5_week',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='lstmforecastedvalue',
            name='next_5_year',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
    ]
