# Generated by Django 4.2 on 2023-05-13 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockforecast', '0015_remove_lstmforecastedvalue_next_five_days_values_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLPForecastedValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('next_1_day', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('next_2_day', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('next_3_day', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('next_4_day', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('next_5_day', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('next_1_week', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('next_2_week', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('next_3_week', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('next_4_week', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('next_5_week', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('next_1_month', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('next_2_month', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('next_3_month', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('next_4_month', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('next_5_month', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('next_1_year', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('next_2_year', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('next_3_year', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('next_4_year', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('next_5_year', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockforecast.stock')),
            ],
        ),
    ]
