# Generated by Django 4.2 on 2023-05-16 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockforecast', '0020_alter_stock_lastprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='exchange',
            field=models.CharField(max_length=50),
        ),
    ]
