# Generated by Django 4.2 on 2023-05-16 01:43

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stockforecast', '0021_alter_stock_exchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='name1',
            field=django_cryptography.fields.encrypt(models.CharField(default='NA', max_length=255)),
        ),
    ]
